### ISSUE TITLE
BTrDB is not available

### ISSUE THREAD

**Issue by xixihaha1995** [gtfierro/giles#46]
Hello developer, it looks like the `Quasar TSDB` has changed to [BTrDB](https://github.com/BTrDB/btrdb-server ).
My questions are:
1. Is `BTrDB `compatible with `giles`?
2. Do you have some alternative TSDB options for `giles`, except for `ReadingDB `and `Quasar TSDB`?

Thank you

**Comment by gtfierro** [comment]
> Is BTrDB compatible with giles?
Yes, but BTrDB has moved into closed-source development at https://www.pingthings.io/

> Do you have some alternative TSDB options for giles, except for ReadingDB and Quasar TSDB?
I would recommend looking at https://www.timescale.com/ or https://www.influxdata.com/ to start, though there are many OSS timeseries databases available nowadays

I have since moved on to other projects, so giles is unmaintained

**Comment by xixihaha1995** [comment]
Hello Gabe.


I'm considering to use "smap workflow" to achieve "read data from building sensors, make a decision, control some building actuators".

Do you know what kind of on-going/maintained projects or even the latest "unmaintained" projects I can start with?
@gtfierro

**Comment by gtfierro** [comment]
What kind of building sensors and actuators are you going to be dealing with? Interacting with these protocols is the first hurdle; after that, you can design a bespoke data solution around one of the many timeseries databases available ow. If you are looking at something like BACnet, I'd recommend https://github.com/ChristianTremblay/BAC0
